### ISSUE TITLE
slurm mapping configuration should be kept

### ISSUE THREAD

**Issue by DCaviedesV** [HPSCTerrSys/TSMP_WorkflowGettingStarted#4]
The information in the `slm_multiprog_mapping.conf` file should be kept, either raw (simply copying to the consolidated log directory) or cast into one of the log files. This information is relevant to document job configurations. 
This should be the case both if the job succeeds or fails

**Comment by kgoergen** [comment]
Now stored as raw information slm_multiprog_mapping.conf with simres/logs.
If you are referring to slurm affinity maps in the context of pinning, a quick test revealed that the change of the default mapping as with the 2024-08-06 slurm upgrade does not show any effect (neither on runtime not on results, remain bit identical).
